name: CMake-Release

on:
  push:
    branches: [ "feat/workflows" ]
  #   branches: [ "main", "development"]
  # pull_request:
  #   branches: [ "main", "development"]

jobs:
  ca:
    name: Coverage Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test Individual
      working-directory: ${{github.workspace}}/build
      run: make test mars-test

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
